region: us-east-1

function_name: manual_email
handler: service.handler
description: Send one-off emails to the list.
runtime: python3.10

aws_access_key_id:
aws_secret_access_key:

timeout: 10
memory_size: 128

environment_variables:
    BOUNCE_EMAIL: test@example.com
